# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fort
email: oliver@lumby.me
description: > # this means to ignore newlines until "baseurl:"
  Fort is a frontend framework built with SCSS and originally ported from Turret by Scott de Jonge.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fort.lumby.me" # the base hostname & protocol for your site
github_path: olumby/fort

# Build settings
markdown: kramdown
